// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxnlFR5BOBWMEt2fvsysjeptZhJ66uelA',
    appId: '1:1027357366510:web:4cf84d57eec543597efbff',
    messagingSenderId: '1027357366510',
    projectId: 'ai-baby-look-alike-creator-app',
    authDomain: 'ai-baby-look-alike-creator-app.firebaseapp.com',
    storageBucket: 'ai-baby-look-alike-creator-app.appspot.com',
    measurementId: 'G-GHBM62BF8M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ04JY4lbH50eC0d86KpedN_CHolSlJ5c',
    appId: '1:1027357366510:android:bcc7c5132db3adc07efbff',
    messagingSenderId: '1027357366510',
    projectId: 'ai-baby-look-alike-creator-app',
    storageBucket: 'ai-baby-look-alike-creator-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr-542WdgOGHLOWBdo_ifFsyEH-x8mg2M',
    appId: '1:1027357366510:ios:d54cc9bb726396c67efbff',
    messagingSenderId: '1027357366510',
    projectId: 'ai-baby-look-alike-creator-app',
    storageBucket: 'ai-baby-look-alike-creator-app.appspot.com',
    iosBundleId: 'com.example.aiBabyLookAlikeCreatorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCr-542WdgOGHLOWBdo_ifFsyEH-x8mg2M',
    appId: '1:1027357366510:ios:d54cc9bb726396c67efbff',
    messagingSenderId: '1027357366510',
    projectId: 'ai-baby-look-alike-creator-app',
    storageBucket: 'ai-baby-look-alike-creator-app.appspot.com',
    iosBundleId: 'com.example.aiBabyLookAlikeCreatorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxnlFR5BOBWMEt2fvsysjeptZhJ66uelA',
    appId: '1:1027357366510:web:be8094e55a4dbd427efbff',
    messagingSenderId: '1027357366510',
    projectId: 'ai-baby-look-alike-creator-app',
    authDomain: 'ai-baby-look-alike-creator-app.firebaseapp.com',
    storageBucket: 'ai-baby-look-alike-creator-app.appspot.com',
    measurementId: 'G-9XECQTWETR',
  );
}
